# Generated by Django 6.0.4 on 2026-04-18 18:50

import string_analyzer_service.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StringAnalysisModel',
            fields=[
                ('id', models.CharField(editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField()),
                ('created_at', models.DateTimeField(default=string_analyzer_service.utils.created_at, editable=False)),
                ('properties', models.JSONField(blank=True)),
            ],
            options={
                'db_table': 'string_analysis_model',
            },
        ),
    ]
