# Generated by Django 6.0.4 on 2026-04-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('string_analyzer_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringanalysismodel',
            name='id',
            field=models.CharField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stringanalysismodel',
            name='value',
            field=models.CharField(editable=False),
        ),
    ]
