# Generated by Django 6.0.4 on 2026-04-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('string_analyzer_service', '0002_alter_stringanalysismodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringanalysismodel',
            name='id',
            field=models.CharField(blank=True, editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
