# Generated by Django 6.0.4 on 2026-04-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('string_analyzer_service', '0003_alter_stringanalysismodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringanalysismodel',
            name='value',
            field=models.CharField(),
        ),
    ]
