# Generated by Django 6.0.4 on 2026-04-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('string_analyzer_service', '0005_alter_stringanalysismodel_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringanalysismodel',
            name='properties',
            field=models.JSONField(default={}),
        ),
    ]
