# Generated by Django 6.0.4 on 2026-04-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('string_analyzer_service', '0008_alter_stringanalysismodel_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringanalysismodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
