# Generated by Django 6.0.5 on 2026-05-20 19:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('capital', models.CharField(blank=True, max_length=250)),
                ('region', models.CharField(blank=True, max_length=250)),
                ('population', models.IntegerField()),
                ('currency_code', models.CharField(max_length=3, null=True)),
                ('exchange_rate', models.FloatField(null=True)),
                ('estimated_gdp', models.FloatField(default=0.0, null=True)),
                ('flag_url', models.URLField(blank=True)),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['region'], name='countries_d_region_9c47a7_idx'), models.Index(fields=['currency_code'], name='countries_d_currenc_ef7914_idx'), models.Index(fields=['estimated_gdp'], name='countries_d_estimat_2d6a12_idx'), models.Index(fields=['-estimated_gdp'], name='countries_d_estimat_1ab91b_idx'), models.Index(fields=['region', 'currency_code', 'estimated_gdp'], name='countries_d_region_d6b8cf_idx'), models.Index(fields=['region', 'currency_code', '-estimated_gdp'], name='countries_d_region_4e8a21_idx')],
            },
        ),
    ]
